// @ts-ignore typescript error for remote import
import React from 'https://cdn.skypack.dev/react';
// @ts-ignore
import ReactDOM from 'https://cdn.skypack.dev/react-dom';

import Layout from './components/Layout/index';

var allMaterialData = {
  Materials: [
    {
      Raw: [
        { Name: 'antimony', Category: '7', Rarity: 'rare', Type: 'Raw' },
        { Name: 'arsenic', Category: '6', Rarity: 'common', Type: 'Raw' },
        { Name: 'boron', Category: '7', Rarity: 'very common', Type: 'Raw' },
        { Name: 'cadmium', Category: '3', Rarity: 'standard', Type: 'Raw' },
        { Name: 'carbon', Category: '1', Rarity: 'very common', Type: 'Raw' },
        { Name: 'chromium', Category: '2', Rarity: 'common', Type: 'Raw' },
        { Name: 'germanium', Category: '5', Rarity: 'common', Type: 'Raw' },
        { Name: 'iron', Category: '4', Rarity: 'very common', Type: 'Raw' },
        { Name: 'lead', Category: '7', Rarity: 'very common', Type: 'Raw' },
        { Name: 'manganese', Category: '3', Rarity: 'common', Type: 'Raw' },
        { Name: 'mercury', Category: '6', Rarity: 'standard', Type: 'Raw' },
        { Name: 'molybdenum', Category: '2', Rarity: 'standard', Type: 'Raw' },
        { Name: 'nickel', Category: '5', Rarity: 'very common', Type: 'Raw' },
        { Name: 'niobium', Category: '1', Rarity: 'standard', Type: 'Raw' },
        { Name: 'phosphorus', Category: '2', Rarity: 'very common', Type: 'Raw' },
        { Name: 'polonium', Category: '6', Rarity: 'rare', Type: 'Raw' },
        { Name: 'rhenium', Category: '6', Rarity: 'very common', Type: 'Raw' },
        { Name: 'ruthenium', Category: '3', Rarity: 'rare', Type: 'Raw' },
        { Name: 'selenium', Category: '4', Rarity: 'rare', Type: 'Raw' },
        { Name: 'sulphur', Category: '3', Rarity: 'very common', Type: 'Raw' },
        { Name: 'technetium', Category: '2', Rarity: 'rare', Type: 'Raw' },
        { Name: 'tellurium', Category: '5', Rarity: 'rare', Type: 'Raw' },
        { Name: 'tin', Category: '4', Rarity: 'standard', Type: 'Raw' },
        { Name: 'tungsten', Category: '5', Rarity: 'standard', Type: 'Raw' },
        { Name: 'vanadium', Category: '1', Rarity: 'common', Type: 'Raw' },
        { Name: 'yttrium', Category: '1', Rarity: 'rare', Type: 'Raw' },
        { Name: 'zinc', Category: '4', Rarity: 'common', Type: 'Raw' },
        { Name: 'zirconium', Category: '7', Rarity: 'common', Type: 'Raw' },
      ],
    },
    {
      Encoded: [
        { Name: 'aberrant shield pattern analysis', Category: 'shield data', Rarity: 'rare', Type: 'Encoded' },
        {
          Name: 'abnormal compact emissions data',
          Category: 'emission data',
          Rarity: 'very rare',
          Type: 'Encoded',
        },
        {
          Name: 'adaptive encryptors capture',
          Category: 'encryption files',
          Rarity: 'very rare',
          Type: 'Encoded',
        },
        { Name: 'anomalous bulk scan data', Category: 'data archives', Rarity: 'very common', Type: 'Encoded' },
        { Name: 'anomalous fsd telemetry', Category: 'wake scans', Rarity: 'common', Type: 'Encoded' },
        {
          Name: 'atypical disrupted wake echoes',
          Category: 'wake scans',
          Rarity: 'very common',
          Type: 'Encoded',
        },
        { Name: 'atypical encryption archives', Category: 'encryption files', Rarity: 'rare', Type: 'Encoded' },
        { Name: 'classified scan databanks', Category: 'data archives', Rarity: 'standard', Type: 'Encoded' },
        { Name: 'classified scan fragment', Category: 'data archives', Rarity: 'very rare', Type: 'Encoded' },
        {
          Name: 'cracked industrial firmware',
          Category: 'encoded firmware',
          Rarity: 'standard',
          Type: 'Encoded',
        },
        { Name: 'datamined wake exceptions', Category: 'wake scans', Rarity: 'very rare', Type: 'Encoded' },
        { Name: 'decoded emission data', Category: 'emission data', Rarity: 'rare', Type: 'Encoded' },
        {
          Name: 'distorted shield cycle recordings',
          Category: 'shield data',
          Rarity: 'very common',
          Type: 'Encoded',
        },
        { Name: 'divergent scan data', Category: 'data archives', Rarity: 'rare', Type: 'Encoded' },
        { Name: 'eccentric hyperspace trajectories', Category: 'wake scans', Rarity: 'rare', Type: 'Encoded' },
        {
          Name: 'exceptional scrambled emission data',
          Category: 'emission data',
          Rarity: 'very common',
          Type: 'Encoded',
        },
        {
          Name: 'inconsistent shield soak analysis',
          Category: 'shield data',
          Rarity: 'common',
          Type: 'Encoded',
        },
        { Name: 'irregular emission data', Category: 'emission data', Rarity: 'common', Type: 'Encoded' },
        { Name: 'modified consumer firmware', Category: 'encoded firmware', Rarity: 'common', Type: 'Encoded' },
        {
          Name: 'modified embedded firmware',
          Category: 'encoded firmware',
          Rarity: 'very rare',
          Type: 'Encoded',
        },
        { Name: 'open symmetric keys', Category: 'encryption files', Rarity: 'standard', Type: 'Encoded' },
        {
          Name: 'peculiar shield frequency data',
          Category: 'shield data',
          Rarity: 'very rare',
          Type: 'Encoded',
        },
        { Name: 'security firmware patch', Category: 'encoded firmware', Rarity: 'rare', Type: 'Encoded' },
        {
          Name: 'specialised legacy firmware',
          Category: 'encoded firmware',
          Rarity: 'very common',
          Type: 'Encoded',
        },
        { Name: 'strange wake solutions', Category: 'wake scans', Rarity: 'standard', Type: 'Encoded' },
        { Name: 'tagged encryption codes', Category: 'encryption files', Rarity: 'common', Type: 'Encoded' },
        { Name: 'unexpected emission data', Category: 'emission data', Rarity: 'standard', Type: 'Encoded' },
        { Name: 'unidentified scan archives', Category: 'data archives', Rarity: 'common', Type: 'Encoded' },
        { Name: 'untypical shield scans', Category: 'shield data', Rarity: 'standard', Type: 'Encoded' },
        {
          Name: 'unusual encrypted files',
          Category: 'encryption files',
          Rarity: 'very common',
          Type: 'Encoded',
        },
      ],
    },
    {
      Manufactured: [
        { Name: 'basic conductors', Category: 'conductive', Rarity: 'very common', Type: 'Manufactured' },
        { Name: 'biotech conductors', Category: 'conductive', Rarity: 'very rare', Type: 'Manufactured' },
        { Name: 'chemical distillery', Category: 'chemical', Rarity: 'standard', Type: 'Manufactured' },
        { Name: 'chemical manipulators', Category: 'chemical', Rarity: 'rare', Type: 'Manufactured' },
        { Name: 'chemical processors', Category: 'chemical', Rarity: 'common', Type: 'Manufactured' },
        { Name: 'chemical storage units', Category: 'chemical', Rarity: 'very common', Type: 'Manufactured' },
        { Name: 'compact composites', Category: 'composite', Rarity: 'very common', Type: 'Manufactured' },
        { Name: 'compound shielding', Category: 'shielding', Rarity: 'rare', Type: 'Manufactured' },
        { Name: 'conductive ceramics', Category: 'conductive', Rarity: 'standard', Type: 'Manufactured' },
        { Name: 'conductive components', Category: 'conductive', Rarity: 'common', Type: 'Manufactured' },
        { Name: 'conductive polymers', Category: 'conductive', Rarity: 'rare', Type: 'Manufactured' },
        {
          Name: 'configurable components',
          Category: 'mechanical components',
          Rarity: 'rare',
          Type: 'Manufactured',
        },
        { Name: 'core dynamics composites', Category: 'composite', Rarity: 'very rare', Type: 'Manufactured' },
        { Name: 'crystal shards', Category: 'crystals', Rarity: 'very common', Type: 'Manufactured' },
        { Name: 'electrochemical arrays', Category: 'capacitors', Rarity: 'standard', Type: 'Manufactured' },
        { Name: 'exquisite focus crystals', Category: 'crystals', Rarity: 'very rare', Type: 'Manufactured' },
        { Name: 'filament composites', Category: 'composite', Rarity: 'common', Type: 'Manufactured' },
        { Name: 'flawed focus crystals', Category: 'crystals', Rarity: 'common', Type: 'Manufactured' },
        { Name: 'focus crystals', Category: 'crystals', Rarity: 'standard', Type: 'Manufactured' },
        { Name: 'galvanising alloys', Category: 'alloys', Rarity: 'common', Type: 'Manufactured' },
        { Name: 'grid resistors', Category: 'capacitors', Rarity: 'very common', Type: 'Manufactured' },
        { Name: 'heat conduction wiring', Category: 'heat', Rarity: 'very common', Type: 'Manufactured' },
        { Name: 'heat dispersion plate', Category: 'heat', Rarity: 'common', Type: 'Manufactured' },
        { Name: 'heat exchangers', Category: 'heat', Rarity: 'standard', Type: 'Manufactured' },
        { Name: 'heat resistant ceramics', Category: 'thermic', Rarity: 'common', Type: 'Manufactured' },
        { Name: 'heat vanes', Category: 'heat', Rarity: 'rare', Type: 'Manufactured' },
        { Name: 'high density composites', Category: 'composite', Rarity: 'standard', Type: 'Manufactured' },
        { Name: 'hybrid capacitors', Category: 'capacitors', Rarity: 'common', Type: 'Manufactured' },
        { Name: 'imperial shielding', Category: 'shielding', Rarity: 'very rare', Type: 'Manufactured' },
        {
          Name: 'improvised components',
          Category: 'mechanical components',
          Rarity: 'very rare',
          Type: 'Manufactured',
        },
        {
          Name: 'mechanical components',
          Category: 'mechanical components',
          Rarity: 'standard',
          Type: 'Manufactured',
        },
        {
          Name: 'mechanical equipment',
          Category: 'mechanical components',
          Rarity: 'common',
          Type: 'Manufactured',
        },
        {
          Name: 'mechanical scrap',
          Category: 'mechanical components',
          Rarity: 'very common',
          Type: 'Manufactured',
        },
        { Name: 'military grade alloys', Category: 'thermic', Rarity: 'very rare', Type: 'Manufactured' },
        { Name: 'military supercapacitors', Category: 'capacitors', Rarity: 'very rare', Type: 'Manufactured' },
        { Name: 'pharmaceutical isolators', Category: 'chemical', Rarity: 'very rare', Type: 'Manufactured' },
        { Name: 'phase alloys', Category: 'alloys', Rarity: 'standard', Type: 'Manufactured' },
        { Name: 'polymer capacitors', Category: 'capacitors', Rarity: 'rare', Type: 'Manufactured' },
        { Name: 'precipitated alloys', Category: 'thermic', Rarity: 'standard', Type: 'Manufactured' },
        { Name: 'proprietary composites', Category: 'composite', Rarity: 'rare', Type: 'Manufactured' },
        { Name: 'proto heat radiators', Category: 'heat', Rarity: 'very rare', Type: 'Manufactured' },
        { Name: 'proto light alloys', Category: 'alloys', Rarity: 'rare', Type: 'Manufactured' },
        { Name: 'proto radiolic alloys', Category: 'alloys', Rarity: 'very rare', Type: 'Manufactured' },
        { Name: 'refined focus crystals', Category: 'crystals', Rarity: 'rare', Type: 'Manufactured' },
        { Name: 'salvaged alloys', Category: 'alloys', Rarity: 'very common', Type: 'Manufactured' },
        { Name: 'shield emitters', Category: 'shielding', Rarity: 'common', Type: 'Manufactured' },
        { Name: 'shielding sensors', Category: 'shielding', Rarity: 'standard', Type: 'Manufactured' },
        { Name: 'tempered alloys', Category: 'thermic', Rarity: 'very common', Type: 'Manufactured' },
        { Name: 'thermic alloys', Category: 'thermic', Rarity: 'rare', Type: 'Manufactured' },
        { Name: 'worn shield emitters', Category: 'shielding', Rarity: 'very common', Type: 'Manufactured' },
      ],
    },
  ],
};

ReactDOM.render(<Layout materialData={allMaterialData} />, document.getElementById('root'));
